version: '3.8'

services:
  chat-proxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@db:5432/chat_proxy}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8000}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chat_proxy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data: