version: '3.8'

services:
  chat-proxy:
    build: .
    container_name: ${CONTAINER_NAME:-n8n-chat-proxy}
    image: n8n-chat-proxy:${IMAGE_TAG:-latest}
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # Override any environment variables if needed
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      # Mount SQLite database file if using SQLite mode
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chat-network:
    name: ${NETWORK_NAME:-n8n-chat-network}
    driver: bridge